require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CardFontColorsController do

  # This should return the minimal set of attributes required to create a valid
  # CardFontColor. As you add validations to CardFontColor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "card_font_color" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CardFontColorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all card_font_colors as @card_font_colors" do
      card_font_color = CardFontColor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:card_font_colors).should eq([card_font_color])
    end
  end

  describe "GET show" do
    it "assigns the requested card_font_color as @card_font_color" do
      card_font_color = CardFontColor.create! valid_attributes
      get :show, {:id => card_font_color.to_param}, valid_session
      assigns(:card_font_color).should eq(card_font_color)
    end
  end

  describe "GET new" do
    it "assigns a new card_font_color as @card_font_color" do
      get :new, {}, valid_session
      assigns(:card_font_color).should be_a_new(CardFontColor)
    end
  end

  describe "GET edit" do
    it "assigns the requested card_font_color as @card_font_color" do
      card_font_color = CardFontColor.create! valid_attributes
      get :edit, {:id => card_font_color.to_param}, valid_session
      assigns(:card_font_color).should eq(card_font_color)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CardFontColor" do
        expect {
          post :create, {:card_font_color => valid_attributes}, valid_session
        }.to change(CardFontColor, :count).by(1)
      end

      it "assigns a newly created card_font_color as @card_font_color" do
        post :create, {:card_font_color => valid_attributes}, valid_session
        assigns(:card_font_color).should be_a(CardFontColor)
        assigns(:card_font_color).should be_persisted
      end

      it "redirects to the created card_font_color" do
        post :create, {:card_font_color => valid_attributes}, valid_session
        response.should redirect_to(CardFontColor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved card_font_color as @card_font_color" do
        # Trigger the behavior that occurs when invalid params are submitted
        CardFontColor.any_instance.stub(:save).and_return(false)
        post :create, {:card_font_color => { "card_font_color" => "invalid value" }}, valid_session
        assigns(:card_font_color).should be_a_new(CardFontColor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CardFontColor.any_instance.stub(:save).and_return(false)
        post :create, {:card_font_color => { "card_font_color" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested card_font_color" do
        card_font_color = CardFontColor.create! valid_attributes
        # Assuming there are no other card_font_colors in the database, this
        # specifies that the CardFontColor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CardFontColor.any_instance.should_receive(:update_attributes).with({ "card_font_color" => "MyString" })
        put :update, {:id => card_font_color.to_param, :card_font_color => { "card_font_color" => "MyString" }}, valid_session
      end

      it "assigns the requested card_font_color as @card_font_color" do
        card_font_color = CardFontColor.create! valid_attributes
        put :update, {:id => card_font_color.to_param, :card_font_color => valid_attributes}, valid_session
        assigns(:card_font_color).should eq(card_font_color)
      end

      it "redirects to the card_font_color" do
        card_font_color = CardFontColor.create! valid_attributes
        put :update, {:id => card_font_color.to_param, :card_font_color => valid_attributes}, valid_session
        response.should redirect_to(card_font_color)
      end
    end

    describe "with invalid params" do
      it "assigns the card_font_color as @card_font_color" do
        card_font_color = CardFontColor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CardFontColor.any_instance.stub(:save).and_return(false)
        put :update, {:id => card_font_color.to_param, :card_font_color => { "card_font_color" => "invalid value" }}, valid_session
        assigns(:card_font_color).should eq(card_font_color)
      end

      it "re-renders the 'edit' template" do
        card_font_color = CardFontColor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CardFontColor.any_instance.stub(:save).and_return(false)
        put :update, {:id => card_font_color.to_param, :card_font_color => { "card_font_color" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested card_font_color" do
      card_font_color = CardFontColor.create! valid_attributes
      expect {
        delete :destroy, {:id => card_font_color.to_param}, valid_session
      }.to change(CardFontColor, :count).by(-1)
    end

    it "redirects to the card_font_colors list" do
      card_font_color = CardFontColor.create! valid_attributes
      delete :destroy, {:id => card_font_color.to_param}, valid_session
      response.should redirect_to(card_font_colors_url)
    end
  end

end
