require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CardImagesController do

  # This should return the minimal set of attributes required to create a valid
  # CardImage. As you add validations to CardImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "image" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CardImagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all card_images as @card_images" do
      card_image = CardImage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:card_images).should eq([card_image])
    end
  end

  describe "GET show" do
    it "assigns the requested card_image as @card_image" do
      card_image = CardImage.create! valid_attributes
      get :show, {:id => card_image.to_param}, valid_session
      assigns(:card_image).should eq(card_image)
    end
  end

  describe "GET new" do
    it "assigns a new card_image as @card_image" do
      get :new, {}, valid_session
      assigns(:card_image).should be_a_new(CardImage)
    end
  end

  describe "GET edit" do
    it "assigns the requested card_image as @card_image" do
      card_image = CardImage.create! valid_attributes
      get :edit, {:id => card_image.to_param}, valid_session
      assigns(:card_image).should eq(card_image)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CardImage" do
        expect {
          post :create, {:card_image => valid_attributes}, valid_session
        }.to change(CardImage, :count).by(1)
      end

      it "assigns a newly created card_image as @card_image" do
        post :create, {:card_image => valid_attributes}, valid_session
        assigns(:card_image).should be_a(CardImage)
        assigns(:card_image).should be_persisted
      end

      it "redirects to the created card_image" do
        post :create, {:card_image => valid_attributes}, valid_session
        response.should redirect_to(CardImage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved card_image as @card_image" do
        # Trigger the behavior that occurs when invalid params are submitted
        CardImage.any_instance.stub(:save).and_return(false)
        post :create, {:card_image => { "image" => "invalid value" }}, valid_session
        assigns(:card_image).should be_a_new(CardImage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CardImage.any_instance.stub(:save).and_return(false)
        post :create, {:card_image => { "image" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested card_image" do
        card_image = CardImage.create! valid_attributes
        # Assuming there are no other card_images in the database, this
        # specifies that the CardImage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CardImage.any_instance.should_receive(:update_attributes).with({ "image" => "MyString" })
        put :update, {:id => card_image.to_param, :card_image => { "image" => "MyString" }}, valid_session
      end

      it "assigns the requested card_image as @card_image" do
        card_image = CardImage.create! valid_attributes
        put :update, {:id => card_image.to_param, :card_image => valid_attributes}, valid_session
        assigns(:card_image).should eq(card_image)
      end

      it "redirects to the card_image" do
        card_image = CardImage.create! valid_attributes
        put :update, {:id => card_image.to_param, :card_image => valid_attributes}, valid_session
        response.should redirect_to(card_image)
      end
    end

    describe "with invalid params" do
      it "assigns the card_image as @card_image" do
        card_image = CardImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CardImage.any_instance.stub(:save).and_return(false)
        put :update, {:id => card_image.to_param, :card_image => { "image" => "invalid value" }}, valid_session
        assigns(:card_image).should eq(card_image)
      end

      it "re-renders the 'edit' template" do
        card_image = CardImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CardImage.any_instance.stub(:save).and_return(false)
        put :update, {:id => card_image.to_param, :card_image => { "image" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested card_image" do
      card_image = CardImage.create! valid_attributes
      expect {
        delete :destroy, {:id => card_image.to_param}, valid_session
      }.to change(CardImage, :count).by(-1)
    end

    it "redirects to the card_images list" do
      card_image = CardImage.create! valid_attributes
      delete :destroy, {:id => card_image.to_param}, valid_session
      response.should redirect_to(card_images_url)
    end
  end

end
